services:

  web:
    image: nginx:1.29.8
    volumes:
      - ./services/gateway:/etc/nginx/conf.d
      - ./services/gateway/static:/usr/share/nginx/static
    command: ["nginx-debug", "-g", "daemon off;"]
    ports:
      - "80:80"

  server:
    build: ./services/server
    env_file:
      - ./services/server/.env