server{
    listen 80;

    root /usr/share/nginx/static;
    index index.html;

    location / {
        try_files $uri $uri/ /index.html;
        
        add_header Cross-Origin-Opener-Policy same-origin-allow-popups;
    }

    location /api {
        proxy_pass http://server:3000/api;
    }
}