server{
    listen 80;

    root /usr/share/nginx/static;
    index index.html;

    location / {
        try_files $uri $uri/ =404;
    }

    location /auth {
        proxy_pass http://auth:3000;
    }
}